export const HttpMessage = {
  CONTINUE: 'Continue',
  SWITCHING_PROTOCOLS: 'Switching protocols',
  PROCESSING: 'Processing',
  EARLY_HINTS: 'Early hints',
  OK: 'Ok',
  CREATED: 'Created',
  ACCEPTED: 'Accepted',
  NON_AUTHORITATIVE_INFORMATION: 'Non authoritative information',
  NO_CONTENT: 'No content',
  RESET_CONTENT: 'Reset content',
  PARTIAL_CONTENT: 'Partial content',
  AMBIGUOUS: 'Ambiguous',
  MOVED_PERMANENTLY: 'Moved permanently',
  FOUND: 'Found',
  SEE_OTHER: 'See other',
  NOT_MODIFIED: 'Not modified',
  TEMPORARY_REDIRECT: 'Temporary redirect',
  PERMANENT_REDIRECT: 'Permanent redirect',
  BAD_REQUEST: 'Bad request',
  UNAUTHORIZED: 'Unauthorized',
  PAYMENT_REQUIRED: 'Payment required',
  FORBIDDEN: 'Forbidden',
  NOT_FOUND: 'Not found',
  METHOD_NOT_ALLOWED: 'Method not allowed',
  NOT_ACCEPTABLE: 'Not acceptable',
  PROXY_AUTHENTICATION_REQUIRED: 'Proxy authentication required',
  REQUEST_TIMEOUT: 'Request timeout',
  CONFLICT: 'Conflict',
  GONE: 'Gone',
  LENGTH_REQUIRED: 'Length required',
  PRECONDITION_FAILED: 'Precondition failed',
  PAYLOAD_TOO_LARGE: 'Payload too large',
  URI_TOO_LONG: 'Uri too long',
  UNSUPPORTED_MEDIA_TYPE: 'Unsupported media type',
  REQUESTED_RANGE_NOT_SATISFIABLE: 'Requested range not satisfiable',
  EXPECTATION_FAILED: 'Expectation failed',
  I_AM_A_TEAPOT: 'I am a teapot',
  MISDIRECTED: 'Misdirected',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  FAILED_DEPENDENCY: 'Failed dependency',
  PRECONDITION_REQUIRED: 'Precondition required',
  TOO_MANY_REQUESTS: 'Too many requests',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  NOT_IMPLEMENTED: 'Not implemented',
  BAD_GATEWAY: 'Bad gateway',
  SERVICE_UNAVAILABLE: 'Service unavailable',
  GATEWAY_TIMEOUT: 'Gateway timeout',
  HTTP_VERSION_NOT_SUPPORTED: 'Http version not supported',
  // new message
  LOING_REQUEST: 'Please Login.',
  DELETE_SAVED_PORT: 'Delete Saved Port Successfully',
  DELETE_ORDER_PORT: 'Delete Order Port Successfully',
  GET_PORT_LIST: 'Get Port List',
  GET_SINGLE_PORT: 'Get Port Successfully',
  POD_NOT_AVAILABLE: 'Pod Is Not FOUND',
  LIMIT_EXIST: 'Your Limit Is Exists',
  PORT_NOT_CREATE: 'Cannot Create Port',
  NOT_UPDATE_DEVICE: 'Port Created But Not Update In Device',
  ERROR_ADMIN_STATUS: 'Admin Status Is Error',
  ADMIN_STATUS_SUCCESS: 'Create Port Successfully.',
  POD_NOT_FOR_PORT: 'Port Not Available For This Pod',
  ORDER_PLACE: 'Please Place Order First',
  LINK_SUCCESS: 'Link Create Successfully.',
  ADMIN_DEPLOYABLE: 'Admin Status Is Not Deployable',
  PORT_UPDATE: 'Port Update Successfully',
  UPDATE_SAVED_PORT: 'Update Saved Port Successfully',
  UPDATE_ORDER_PORT: 'Update Order Port Successfully',
  ADMIN_STATUS_CHANGE: 'Admin Status Changed Successfully',
  CONNECTON_NAME_ALREADY_EXIST: 'Connection Name Is Already Exist',
  SOURCE_PORT_NOT_EXIST: 'Source Id Is Not Available',
  DESTINATION_PORT_NOT_EXIST: 'Destination Id Not Available',
  ACTIVE_SOURCE_PORT: 'Please Activate The Source.',
  ACTIVE_DESTINATION_PORT: 'Please Activate The Destination.',
  PORT_TYPE: 'Type Is Not Port',
  CE_VLAN_NOT_IN_SOURCE: 'Ce_vlan Not Available For Source',
  CE_VLAN_NOT_IN_DESTINATION: 'Ce_vlan Not Available For Destination ',
  GLOBAL_OBJECT_NOT_FOUND: 'Global Object Is Not Found',
  GET_CONNECTION_LIST: 'Get Connection List',
  CONNECTION_NOT_FOUND: 'Connection Is Not Found',
  SOURCE_DEVICE_NOT_EXIST: 'Source Device Id Is Not Available',
  DESTINATION_DEVICE_NOT_EXIST: 'Destination Device Id Not Available',
  CONNECTION_UPDATE_SUCCESSFULLY: 'Connection Updated Successfully',
  CONNECTION_DELETED_SUCCESSFULLY: 'Connection Deleted Successfully',
  // FCR
  GET_FCR_LIST: 'Get Fcr List Successfully.',
  FCR_EXIST: 'FCR Name Already Exist.',
  REGION_NOT_EXIST: 'Region Not Found.',
  DATACENTER_NOT_EXIST: 'Datacenter Not Found.',
  FCR_CREATED: 'FCR Created Successfully.',
  FCR_NOT_FOUND: 'FCR_NOT_FOUND',
  FCR_UPDATED: 'FCR Updated Successfully.',
  FCR_DELETED: 'Fcr Deleted Succcessfully.',
  CHECK_ORG_CODE: 'Unable To Create FCR With Same Organization.',
  FCR_ALREADY_EXIST_IN_CONNECTION:
    'FCR Is Already Used In Connection, You Cannot Delete It.',
  LOG_BY_FCR_ID: 'Get Log List By Fcr Id.',
  // Log Message
  LOG_NOT_FOUND: 'Log Not Found',
  GET_LOG_LIST: 'Get Log List',
  // connections
  GET_PORT_PORT_TYPE: 'Get All Ports With Type Port.',
  GET_FCR_FCR_TYPE: 'Get All FCR With Type FCR',
  GET_CONNECTION_BASED_PORT_ID: 'Get All Connection Data Based On PortId.',
  SAME_REGION_CONNECTION: 'You Cant Create Connection with Same Region.',
  CE_VLAN_REQUIRED: 'v_lan id is required in both end',
  A_CE_VLANID_REQUIRED: 'a_end_vlan_id Is Required',
  B_CE_VLANID_REQUIRED: 'b_end_vlan_id Is Required',
  INVALID_SOURCE_ID: 'Invaild Source Id.',
  ORG_NOT_FOUND: 'Organization Is Not Found.',
  SOURCE_CE_VLAN_ALREADY_USED: 'Vlan Id Is Already Used In Source.',
  DESTINATION_CE_VLAN_ALREADY_USED: 'Vlan ID Is Already Used In Destination',
  SUBNET_REQUIRED: 'Subnet Is Required',
  CONNECTION_CREATED: 'Connection Created Successfully.',
  SPEED_NOT_IN_SOURCE: 'Is Not Available In Source',
  SPEED_NOT_IN_DESTINATION: 'Is Not Available In Destination',
  SPEED_NOT_IN_SOURCE_INTERFACE: 'Is Not Exist In Source Interface',
  SPEED_NOT_IN_SOURCE_THROUGHPUT: 'Is Not Exist In Source Throughput.',
  SPEED_NOT_IN_DESTINATION_INTERFACE: 'Is Not Exist Destination Interface.',
  SPEED_NOT_IN_DESTINATION_THROUGHPUT: 'Is Not Exist Destination Throughput.',
  MATCH_ORG: 'Orgnization Must Be Same In Connection.',
  LOG_BY_CONN_ID: 'Get Log List By Connection Id.',
  VLAM_ID_REQUIRED: 'Vlan Id Is Required',
  // based on org code available and used fcr, port, connection
  GET_USED_PORT_DETAILS: 'Get Active And Inactive Ports.',
  GET_USED_FCR_DETAILS: 'Get Active And Inactive Fcr.',
  GET_USED_CONNECTION_DETAILS: 'Get Active And Inactive Vxc.',
  // SUBNET_REQUIRED: 'Subnet Is Required',
  // PORT
  UPDATE_ADMIN_STATUS: 'Please Check admin_status.',
  PORT_NOT_BUL_DELETED: 'Cannot Delete.',
  PORT_BULK_DELETE: 'Delete All Port Successfully.',
  PORT_USED_IN_CONN:
    'Port Is Already Used In Connection, You Cannot Delete It.',
  PORT_NAME_ALREDY_EXIST: 'Port Name Is Already Exist.',
  PORT_CREATE_LIMIT: 'Port Create Limit Exist.',
  LOG_BY_PORT_ID: 'Get Log List By Port Id.',
  CHECK_MINTERM: 'You Can Not Update Minterm Less Then Privious.',
  // add to cart port
  POD_NOT_PRESENT: 'Pod Is Not Present',
  NOT_SAVE_CONFIGRATION: 'Cannot Save The Configrations.',
  CONFIGRATION_SAVED: 'Configration Saved',
  // bgp message
  BGP_ADDED_SUCCESSFULLY: 'Bgp Added Successfully.',
  GET_BGP_LIST: 'Get Bgp List Successfully.',
  BGP_NOT_FOUND: 'Bgp Data Not found.',
  BGP_DELETED: 'Delete Bgp Successfully.',
  BGP_UPDATED: 'Update Bgp Successfully.',
  // datacenter message
  DATACENTER_CREATED: 'Datacenter Created Successfully.',
  GET_DATACENTER: 'Get All Datacenter Successfully.',
  GET_DATACENTER_BY_ID: 'Get Datacenter By Id.',
  GET_DATACENTER_BY_REGION: 'Data Center By Region Id.',
  DATACENTER_NOT_FOUND: 'Datacenter Not Found.',
  DATACENTER_DELETED: 'Datacenter Deleted Successfully.',
  DATACENTER_NOT_BULK_DELETED: 'Canot Delete.',
  DETACENTER_BULK_DELETED_SUCESSFULLY: 'Delete All Datacenter Successfully.',
  DATACENTER_UPDATED: 'Update Datacenter Successfully.',
  DATACENTER_NOT_CREATE: 'Can Not Create Datacenter',
  // pod message
  POD_NOT_ADDED: 'Cannot Add Pod Data.',
  POD_ADDED: 'Pod Added Succesfully.',
  POD_NOT_FOUND: 'Pod Data Not Found.',
  GET_ALL_POD_DATA: 'Get All Pod List Susscessfully.',
  POD_DELETED: 'Pod deleted successfully.',
  POD_NOT_BULK_DELETED: 'Canot Delete',
  POD_BULK_DELETED_SUCESSFULLY: 'Delete All Pod Successfully.',
  POD_UPDATED_SUCCESSUFULLY: 'Pod Updated Successfully.',
  // minterm message
  MINTERM_ADDED: 'Minterm Added',
  MINTERM_NOT_ADDED: 'Canot Minterm Added.',
  MINTERM_NOT_FOUND: 'MINTERM NOT FOUND.',
  GET_MINTERM_LIST: 'Get All Minterm List Successfully.',
  // region
  REGION_NOT_CREATED: 'Cannot Add Region',
  REGION_CREATED: 'Region Created Successfully.',
  REGION_NOT_FOUND: 'Region Not Found.',
  GET_ALL_REGION: 'Get All Region List Successfully.',
  GET_REGION_BY_ID: 'Get Region By Id Successfully.',
  REGION_DELETED: 'Region Deleted Successfully.',
  REGION_BULK_NOT_DELETED: 'Canot Delete Region.',
  REGION_BULK_DELETED: 'All Region Deleted Successfully.',
  REGION_UPDATE_SUCCESSFULLY: 'Region Updated Successfully.',
  // login
  USER_LOGIN: 'User Login Successfully.',
  USER_NOT_CREATE: 'Unable To Create User.',
  USER_ALREADY_EXIST: 'Already Exist',
  // vrfGlobal
  VF_CREATED: 'Vrf Created Successfully.',
  // OrG
  GET_ORG_SUCCESSFULLY: 'Get Org List Successfully.',
};
